<a href="https://colab.research.google.com/github/yograi343/PyTorch-learn/blob/main/00_pytorch__fundamental_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch notebook

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors
Creating tensors
pytorch tensors are created using torch.Tensor()

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[2,3,4],
                       [4,5,3],
                       [4,4,5]]])
TENSOR

tensor([[[2, 3, 4],
         [4, 5, 3],
         [4, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[2, 3, 4],
        [4, 5, 3],
        [4, 4, 5]])

In [ ]:
TENSOR[0,0,1]

tensor(3)

In [ ]:
#TENSOR
TENSOR2 = torch.tensor([[[2,3,4],
                       [4,5,3],
                       [4,4,5]],
                        [[2,3,4],
                       [4,5,3],
                       [4,4,5]]])
TENSOR2

tensor([[[2, 3, 4],
         [4, 5, 3],
         [4, 4, 5]],

        [[2, 3, 4],
         [4, 5, 3],
         [4, 4, 5]]])

In [ ]:
TENSOR2.ndim

3

In [ ]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR2[1,1,2]

tensor(3)

### Random Tensors'
Why random tensors?

Random tensors are important becuase the way many neural networs learn is that they start with tensors full of random numbers and then adjust those random numbers to better those random numbers to better represent the data.


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6736, 0.5004, 0.0196, 0.4582],
        [0.7278, 0.2163, 0.7189, 0.7944],
        [0.6345, 0.9840, 0.9332, 0.8727]])

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))#height, width, colour channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
#Exercise to create my own random tensor
random_tensor_my= torch.rand((3,4,2))
random_tensor_my.shape,random_tensor_my.ndim

(torch.Size([3, 4, 2]), 3)

## Zeros and ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(2,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensor & Tensor-like

In [ ]:
#use torch.range()
one_to_ten = torch.arange(1,11,1,dtype=torch.float64)
one_to_ten

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)

In [ ]:
one_to_ten.dtype

torch.int64

In [ ]:
#create tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
rand_like2 =torch.rand_like(one_to_ten)
rand_like2

tensor([0.8210, 0.3593, 0.1914, 0.1959, 0.2986, 0.2698, 0.5677, 0.6783, 0.2810,
        0.7516], dtype=torch.float64)

## Tensor Datatypes
**Note** Tensor datatypes is one of the 3 big errors you'll run into with pyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,5.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients

float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 9.], dtype=torch.float16)

In [ ]:
 xdf = float_16_tensor* float_32_tensor
 xdf.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,4,2],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 2], dtype=torch.int32)

In [ ]:
int_32_tensor*float_32_tensor

tensor([ 9., 20., 18.])

### Getting information from tensors
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
int_32_tensor.device

device(type='cpu')

In [ ]:
float_32_tensor.shape

torch.Size([3])

In [ ]:
some_tensor = torch.rand([3,4])
some_tensor

tensor([[0.5807, 0.2724, 0.4581, 0.7834],
        [0.6286, 0.5935, 0.1253, 0.1083],
        [0.8441, 0.4756, 0.1076, 0.5007]])

In [ ]:
print(some_tensor)
print(f"Datatypes of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6321, 0.1649, 0.7289, 0.6439],
        [0.6873, 0.4091, 0.7595, 0.2746],
        [0.5533, 0.6537, 0.9672, 0.9610]])
Datatypes of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+100

tensor([11, 12, 13])

In [ ]:
# Multipy tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# subtract tensor by
tensor -10

tensor([-9, -8, -7])

In [ ]:
# try out pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication
Two main ways of performing multiplication in neural networs & deep learning.
* Element-wise multiplication
* Multiply one Matrix by another matrix

there are two rules that performing multiplication needs to satisfy:
1. The **Inner dimension** must match:
* `(3,2)@(3,2)` won't work
* `(2,3)@(3,1)` will work
* `(3,2)@(2,3)` will work
2. the resulting matrix has the shape of the **Outer dimension**:

In [ ]:
A= torch.tensor([[1,2,3],
          [7,8,9]])
B = torch.tensor([[3,4],
                 [7,9],
                 [3,7]])
torch.matmul(A,B)

tensor([[ 26,  43],
        [104, 163]])

In [ ]:
torch.matmul(B,A)

tensor([[ 31,  38,  45],
        [ 70,  86, 102],
        [ 52,  62,  72]])

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,3))

tensor([[1.5703, 0.5360, 1.2104],
        [0.8536, 0.1715, 1.1170]])

## One of the most common errors in deep learning: shape errors

In [ ]:
tensor_A = torch.tensor([[2,3],
                        [3,4],
                        [8,4]])

tensor_B=torch.tensor([[3,4],
                       [7,3],
                       [3,4]])

torch.matmul(tensor_A,tensor_B.T)

tensor([[18, 23, 18],
        [25, 33, 25],
        [40, 68, 40]])

To fix our tensor shape issues, we can manipulate the shape of one our tensors using a transpose
A transpose switches the axes or dimenstion of given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[3, 7],
         [4, 3],
         [5, 5]]),
 torch.Size([3, 2]))

## Finding the min,max,mean,sum,etc (tensor Aggregation)

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#finad the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
#find the Max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Find the positional min and max

In [ ]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[x.argmax()]

tensor(90)

## Reshaping, Stacking, Squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* view  - retur a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stack - combine multiple tensors on top of each other ( vstack ) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# lets create a tensor
import torch
x =torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(1,3,3)
x_reshaped, x_reshaped.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# change the view
x_view = x.view(1,9)
x_view,x_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing x_view changes x ( because a view of a tensor shares the same memory as the original)
x_view[:,0]=5
x_view,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked,x_stacked.shape
x_stacked=x_stacked.reshape(1,9,4)
x_stacked,x_stacked.shape

(tensor([[[1., 1., 1., 1.],
          [2., 2., 2., 2.],
          [3., 3., 3., 3.],
          [4., 4., 4., 4.],
          [5., 5., 5., 5.],
          [6., 6., 6., 6.],
          [7., 7., 7., 7.],
          [8., 8., 8., 8.],
          [9., 9., 9., 9.]]]),
 torch.Size([1, 9, 4]))

In [ ]:
x_stacked.squeeze().shape

torch.Size([9, 4])

In [ ]:
z = torch.zeros(2, 1, 2, 1, 2)
print(z.size())
y = torch.squeeze(z)
print(y.size())
y = torch.squeeze(z, 0)
print(f'squeez with 0 {y.size()}')
y = torch.squeeze(z, 1)
print(f'squeez with 1 {y.size()}')
y = torch.squeeze(z, (1, 2, 3))
print(f'squeez with 1,2,3 {y.size()}')

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
squeez with 0 torch.Size([2, 1, 2, 1, 2])
squeez with 1 torch.Size([2, 2, 1, 2])
squeez with 1,2,3 torch.Size([2, 2, 2])


In [ ]:
n = torch.unsqueeze(z,0)
n.shape

torch.Size([1, 2, 1, 2, 1, 2])

In [ ]:
ex = torch.randn(2,3,5)
print(f'Original Tensor: {ex}')
print(f'Orginal Tensor Shape: {ex.shape}')
ex_permuted = torch.permute(ex,(2,0,1))
print(f'Permuted Tensor: {ex_permuted}')
print(f'Shape of Permuted tensor: {ex_permuted.shape}')

Original Tensor: tensor([[[ 0.4816,  0.5514, -0.1926,  2.0549,  2.1551],
         [-1.0566,  1.1311,  0.4077,  0.0541, -0.6142],
         [ 0.8483,  0.1150, -0.1080,  0.4162, -0.8775]],

        [[-0.8785,  0.9796, -0.7871,  0.4591,  0.5524],
         [-0.1628, -0.6642,  0.3299, -2.0611, -1.2340],
         [ 0.7047, -0.4268, -1.8481, -0.0791, -0.2344]]])
Orginal Tensor Shape: torch.Size([2, 3, 5])
Permuted Tensor: tensor([[[ 0.4816, -1.0566,  0.8483],
         [-0.8785, -0.1628,  0.7047]],

        [[ 0.5514,  1.1311,  0.1150],
         [ 0.9796, -0.6642, -0.4268]],

        [[-0.1926,  0.4077, -0.1080],
         [-0.7871,  0.3299, -1.8481]],

        [[ 2.0549,  0.0541,  0.4162],
         [ 0.4591, -2.0611, -0.0791]],

        [[ 2.1551, -0.6142, -0.8775],
         [ 0.5524, -1.2340, -0.2344]]])
Shape of Permuted tensor: torch.Size([5, 2, 3])


In [ ]:
ex[0,0,0]=34

In [ ]:
ex

tensor([[[34.0000,  0.5514, -0.1926,  2.0549,  2.1551],
         [-1.0566,  1.1311,  0.4077,  0.0541, -0.6142],
         [ 0.8483,  0.1150, -0.1080,  0.4162, -0.8775]],

        [[-0.8785,  0.9796, -0.7871,  0.4591,  0.5524],
         [-0.1628, -0.6642,  0.3299, -2.0611, -1.2340],
         [ 0.7047, -0.4268, -1.8481, -0.0791, -0.2344]]])

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0,1,0]

tensor(4)

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch Tensors & NumPy

NumPy is a Popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy ->torch.Tensor.numpy()

In [ ]:
# Numpy Array to tensor
import torch
import numpy as np

array= np.arange(1.0,8.0)
tensor=torch.from_numpy(array) # Warning: when converting from numpy to pytorch, pytorch reflects it in float64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
#change the value of array, what will this do to `tensor`?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor, what happens to `numpy tensor`?
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In Short how a neural network learns:

`start with random numbers -> tenser operations -> update random numbers to try and make them better representations of the data -> again -> again -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# create two random tensors
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA==random_tensorB)

tensor([[0.3392, 0.1567, 0.1642, 0.0441],
        [0.6774, 0.8913, 0.1496, 0.7700],
        [0.0809, 0.1104, 0.6751, 0.7143]])
tensor([[0.6032, 0.4892, 0.0543, 0.4882],
        [0.8160, 0.7846, 0.8907, 0.3859],
        [0.6131, 0.2691, 0.7395, 0.1627]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make some random but reproducible tensors
import torch

# set the random seed
random_seed = 42
torch.manual_seed(random_seed)

random_tensor_c = torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scense to make every thing hunky dory(good).

### 1. Getting a GPU
1. Easiest - Use Google colab for a free GPU ( options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires investment of purchasing a GPU, there's lots of options
3. Use cloud computing - GCP, AWS, Azure these services allow you to rent computers on the cloud and access them

In [ ]:
!nvidia-smi

Wed Mar 20 07:44:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU acces with PyTorch

In [ ]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device  = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# create a tensor default on the CPU
tensor =torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# if tensor on GPU we want to switch it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix the issue when tensor on gpu to switch to numpy first device needs to be switched to CPU
tensor_on_gpu.to('cpu').numpy()

array([1, 2, 3])

## 00. PyTorch Fundamentals Exercise
# 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on `torch.Tensor`.
* The documentation on `torch.cuda``.

In [ ]:
import torch

In [ ]:
t1=torch.tensor([[1.,-1.],[2.,-2.]],device=device,dtype=torch.float64)# tensor have default datatype as float32
t1,t1.dtype,t1.shape,t1.device

(tensor([[ 1., -1.],
         [ 2., -2.]], device='cuda:0', dtype=torch.float64),
 torch.float64,
 torch.Size([2, 2]),
 device(type='cuda', index=0))

In [ ]:
import numpy as np
t2=torch.tensor(np.array([[2.,3.,4.],[2.,5.,8.]]),device=device)#defalut from numpy is float 64
t2,t2.dtype,t2.shape,t2.device

(tensor([[2., 3., 4.],
         [2., 5., 8.]], device='cuda:0', dtype=torch.float64),
 torch.float64,
 torch.Size([2, 3]),
 device(type='cuda', index=0))

In [ ]:
torch.matmul(t1,t2)

tensor([[ 0., -2., -4.],
        [ 0., -4., -8.]], device='cuda:0', dtype=torch.float64)

In [ ]:
x=torch.tensor([[2.,-1.],[1.,1.]],requires_grad=True)
out = x.pow(2).sum()
print(out)
out.backward()
print(out)
print(x.grad)
print(x)

tensor(7., grad_fn=<SumBackward0>)
tensor(7., grad_fn=<SumBackward0>)
tensor([[ 4., -2.],
        [ 2.,  2.]])
tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [ ]:
t2.H,t2,t2.T

(tensor([[2., 2.],
         [3., 5.],
         [4., 8.]], device='cuda:0', dtype=torch.float64),
 tensor([[2., 3., 4.],
         [2., 5., 8.]], device='cuda:0', dtype=torch.float64),
 tensor([[2., 2.],
         [3., 5.],
         [4., 8.]], device='cuda:0', dtype=torch.float64))

In [ ]:
tensor = torch.ones((2,),dtype=torch.float64)
tensor

tensor([1., 1.], dtype=torch.float64)

In [ ]:
tensor.new_full((3,4),7)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]], dtype=torch.float64)

In [ ]:
tensor

tensor([1., 1.], dtype=torch.float64)

In [ ]:
tensor.is_cuda

False

In [ ]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])

In [ ]:
tensor.grad

In [ ]:
tensor.ndim

1

In [ ]:
x.real,tensor.nbytes,tensor.itemsize,x.itemsize,torch.add(x,1)

(tensor([[ 2., -1.],
         [ 1.,  1.]], requires_grad=True),
 16,
 8,
 4,
 tensor([[3., 0.],
         [2., 2.]], grad_fn=<AddBackward0>))

##2. Create a random tensor with shape (7, 7).

In [ ]:
# Import torch
import torch

# Create a tensor with random shape(7,7)
tensor77=torch.rand(7,7)
tensor77,tensor77.shape

(tensor([[0.3238, 0.0800, 0.3273, 0.0837, 0.4449, 0.1434, 0.4473],
         [0.1560, 0.9077, 0.1551, 0.5781, 0.8278, 0.6455, 0.4623],
         [0.9281, 0.7327, 0.7749, 0.8580, 0.8586, 0.5795, 0.1131],
         [0.2994, 0.1069, 0.8743, 0.5392, 0.3233, 0.8300, 0.2501],
         [0.2629, 0.0559, 0.8530, 0.3829, 0.8381, 0.9444, 0.1232],
         [0.0841, 0.5926, 0.6919, 0.0810, 0.3743, 0.4202, 0.9096],
         [0.6636, 0.7450, 0.5126, 0.8858, 0.6645, 0.0824, 0.5365]]),
 torch.Size([7, 7]))

# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor17 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor17,tensor77)

tensor([[1.7575, 1.6287, 2.7832, 1.8469, 2.5603, 2.1600, 1.6366]])

In [ ]:
torch.matmul(tensor77,tensor17.T)

tensor([[1.2585],
        [1.9751],
        [3.0142],
        [2.2337],
        [2.5814],
        [1.7768],
        [2.2493]])

In [ ]:
# set Manual seed
seed = 42
torch.manual_seed(seed)
#create two random tensors
tensor1 = torch.rand(1,7)
torch.manual_seed(seed)
tensor2 = torch.rand(1,7)

print(f'First tensor {tensor1}')
print(f'2nd tensor {tensor2}')
print(tensor1==tensor2)

First tensor tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
2nd tensor tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
tensor([[True, True, True, True, True, True, True]])


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
#set random seed
torch.manual_seed(1234)
#check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

#create two random tesnors on GPU

a=torch.rand(2,3,device=device)
b=torch.rand(2,3,device=device)
print(a)
print(b)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [ ]:
torch.matmul(a,b.T), torch.matmul(a,b.T).shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

In [ ]:
x = torch.matmul(a,b.T)
x.max(),x.min()

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

In [ ]:
x.argmax(), x.argmin()

(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [ ]:
# Set seed
seed=7
torch.manual_seed(seed)

# Create random tensor
a = torch.rand(1,1,1,10)


print(a)
# Remove single dimensions
a_squeeze =a.squeeze()

# Print out tensors and their shape
print(a_squeeze)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
